version: '3'
services:
  scraper:
    build: .
    command: scrapy crawl reality_spider
    volumes:
      - .:/app
    ports:
      - 5800:5800  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432