# Generated by Django 4.0.4 on 2023-05-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=600)),
                ('img_url', models.TextField(max_length=600)),
                ('prod_url', models.TextField(max_length=600)),
            ],
        ),
    ]
