# Generated by Django 4.0.4 on 2023-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_url',
        ),
    ]
